language: csharp
solution: Pluralize.sln
install:
  - nuget restore Pluralize.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
  - nuget install coveralls.net -Version 0.7.0 -OutputDirectory coveralls
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory opencover
script:
  - xbuild /p:Configuration=Release Pluralize.sln
  - mono "./opencover/OpenCover.*/tools/OpenCover.Console.exe" -target:"./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe" -targetargs:"./Pluralize.NET.Tests/bin/Release/Pluralize.NET.Tests.dll" -register:user filters:"+[Pluralize.NET]*-[Pluralize.NET.Tests]*" -output:"./CodeCoverageResult.xml"
  - mono "./coveralls/coveralls.net.*/tools/csmacnz.Coveralls.exe" --opencover -i ./CodeCoverageResult.xml
